### PR TITLE
Add <code> wrapping button

### PR DESCRIPTION
**Pull request by agentydragon**
Hi!

I'd like to add a button and shortcut to wrap text in `<code>`. Looks like #6 is about requesting inline `<code>`, too.

Unfortunately my implementation does not allow undoing that once it's done.

I've played around a bit with JavaScript to try to remove the the `<code>` tag if it's already present, but it seems to be hard.

Do you think it would be good enough to merge like this, even if it's not undoable (without editing HTML manually)?

#### Description

Add wrappinng of selected text in `<code>`.

My use-case is that I use `<pre>` for longer code samples, but `<code>` for inline code.

I've tested this on the Anki packaged in my Ubuntu installation - 2.1.8.

Unfortunately, there is no `document.execCommand` for adding a `<code>` tag, so I just wrap the selection in `<code>...</code>`. Unfortunately, once you do that, there's no easy way to undo that - both Ctrl+Z and another press of Ctrl+Shift+ will not remove the `<code>...</code>`.

Looking at the source code of the Anki 2.0 addon Power Format Pack (https://gitlab.com/neftas/supplementary-buttons-anki/blob/master/power_format_pack/utility.py#L820), it looks like it is not able to remove the `<code>...</code>` wrapping once inserted, either.

#### Checklist:

*Please replace the space inside the brackets with an **x** and fill out the ellipses if the following items apply:*

- [x] I've read and understood the [contribution guidelines](./CONTRIBUTING.md)
- [ ] I've tested my changes against at least one of the following [Anki builds](https://apps.ankiweb.net/#download):
  - [ ] Latest standard Anki 2.1 binary build [required for Anki-compatible 2.1 add-ons]
  - [ ] Latest alternative Anki 2.1 binary build
  - [ ] Latest Anki 2.0 binary build [required for Anki 2.0-compatible add-ons]
- [x] I've tested my changes on at least one of the following platforms:
  - [x] Linux, version:
  - [ ] Windows, version:
  - [ ] macOS, version: 
- [ ] My changes potentially affect non-desktop platforms, of which I've tested:
  - [ ] AnkiMobile, version:
  - [ ] AnkiDroid, version:
  - [ ] AnkiWeb

### CODE REVIEW

**Comment by caguettaz** [comment]
Hey,

Good idea, but [ctrl] + [shift] + [.] doesn't work on french keyboards since on these one needs to hold shift to type periods.

Why not use [ctrl] + [,] instead, which is what the formatting power pack uses?

Also, the power pack uses the 'code' css class to both <pre> and <code>, which is nice for code-related css.

Check out my https://github.com/caguettaz/mini-format-pack/tree/code-formatting-tweaks branch, which does pretty much that, but base on #17.

**Comment by agentydragon** [comment]
@caguettaz Updated to use Ctrl+, and also asked @glutanimate to take a look at this PR again over email.

**Review by glutanimate — APPROVED** [review]
My apologies again for taking so long to respond to this! I had jotted down a note to look at what you mentioned about removing the code tag if present, and then just never got to it. Really sorry about that.

In any case, I just gave this a try and all seems to be working well. Even undoing seems to work (to the extent that you can Ctrl+Z; once you're past the undo stack you can't use the button to toggle the formatting, but that's completely fine I think).

So, yeah, great work!

I will merge this and then perhaps just tweak the button a bit by adding an icon (I think PFP had one for that exact purpose).

**Comment by agentydragon** [comment]
Thanks! <3

**Comment by agentydragon** [comment]
@glutanimate can you please ping this thread when you release this in a new version?

**Comment by glutanimate** [comment]
@agentydragon will do!

**Pull request merged**
