### PR TITLE
inline-code-block

### PR DESCRIPTION
**Pull request by lukkea**
added inline code block

### CODE REVIEW

**Comment by lukkea** [comment]
this pr adds a button that will wrap currently selected text in <code></code> tags which will create an inline code block.

**Comment by caguettaz** [comment]
Hi @glutanimate, is there a reason this has not been pulled?

This looks useful, and is one of the two features requested in #6.

**Comment by glutanimate** [comment]
@caguettaz 

Hmm, good question. I think I wasn't as keen about 90d310a63acc277c8a4610ab5af90620badb469c because it introduced a few too many additional buttons (and also contained some hotkey conflicts). I thought I had left a comment on that, but obviously I didn't. Sorry about that!

Will look into cherry picking the first commit for the merge as I feel this would be a good addition to the add-on. Thanks again for your contribution @lukkea .

**Comment by lukkea** [comment]
np @glutanimate - I didn't realise my later commits would be included in the pr. is there anything I can do to make this easier for you?

**Comment by glutanimate** [comment]
@lukkea Thanks for jumping in! If you have the time, you could cherry-pick the first commit of this PR into a new branch, and then resubmitting that as a new PR. See here for instance: https://stackoverflow.com/a/25955829/1708932

I could also cherry-pick the commit on my end, but it won't be as neat as it would bypass GitHub's PR system

**Comment by lukkea** [comment]
@glutanimate will do. probably won't be today though - meetings, meetings meetings!

**Comment by lukkea** [comment]
finally got around to fixing this.

new pr here : https://github.com/glutanimate/mini-format-pack/pull/16

**Pull request closed without merging**
